apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-argo
  template:
    metadata:
      labels:
        app: web-argo
    spec:
      containers:
      - name: web-argo
        image: 029290955601.dkr.ecr.ap-northeast-2.amazonaws.com/web-argo:1
        ports:
        - containerPort: 80
